var message = 'тут значение';
var TextString = 'Тут значение String';
var TextNumber = 123456;
var numberBig = 1234563333333333333333333333333333n;
var boolean = false;
alert('Добро пожаловать');
alert('У меня есть 4 переменных с разными типами данных');
alert(TextString);
alert(typeof TextString);
alert(TextNumber);
alert(typeof TextNumber);
alert(numberBig);
alert(typeof numberBig);
alert(boolean);
alert(typeof boolean);
var answerUser = confirm('Понравился ли Вам сайт?');
alert(answerUser);
